name: Home Price Scraper
on:
  schedule:
    # This rotating schedule simulates a ~38 hour gap:
    # Day 1: 12:00 PM (Noon)
    # Day 3: 02:00 AM (38 hours later)
    # Day 4: 04:00 PM (38 hours later)
    - cron: '0 12 1,4,7,10,13,16,19,22,25,28 * *'
    - cron: '0 2 3,6,9,12,15,18,21,24,27,30 * *'
    - cron: '0 16 4,7,10,13,16,19,22,25,28 * *'
  workflow_dispatch: # Keeps your manual "Run" button active

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests gspread oauth2client
      - name: Run Script
        env:
          RENTCAST_API_KEY: ${{ secrets.RENTCAST_API_KEY }}
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
        run: python tracker.py
